OneRow/UI/Models/ErrorViewModel.cs
namespace UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

OneRow/UI/Controllers/AdminController.cs
using Dal.Concrete;
using Entity.Concrete;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace UI.Controllers
{
    public class AdminController : Controller
    {

        Context context = new Context();
        [AllowAnonymous]
        [HttpGet]
        public IActionResult Index()
        {
           
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Index(Admin p)
        {
            var information = context.Admins.FirstOrDefault(x=>x.User_Name==p.User_Name && x.User_Password==p.User_Password);
            if (information!=null)
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, p.User_Name),
                };
                var useridentity= new ClaimsIdentity(claims,"Login");
                ClaimsPrincipal principal= new ClaimsPrincipal(useridentity);
                await HttpContext.SignInAsync(principal);
                
             
                return RedirectToAction("Index","Product");

            }
            return View();
        }
    }
}

OneRow/UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using UI.Models;

namespace UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

OneRow/UI/Controllers/PartController.cs
using Bll.Concrete;
using Dal.Concrete;
using Dal.EntityFramework;
using Entity.Concrete;
using Entity.DTO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace UI.Controllers
{
    
    public class PartController : Controller
    {
       
        SparePartManager sp = new SparePartManager(new EfSparePartRepository());
        ProductManager pm = new ProductManager(new EfProductRepository());
        Context context = new Context();
        [Authorize]
        public IActionResult Index()
        {
            List<SparePart> spareParts = new List<SparePart>();
            spareParts = sp.GetList();
            var list = sp.GetSparePartList();
            return View(list);
           
        }
        public IActionResult PartDelete(int id)
        {
           
            var sparepart = sp.GetById(id);
            sp.ProductDelete(sparepart);
            TempData["infoproductdelete"] = string.Format("{0} Part Deleted.: {1}", sparepart.Part_Name, DateTime.Now.ToString());
            return RedirectToAction("Index");

        }
        [HttpGet]
        public IActionResult AddPart(int id)
        
        {
            SparePart sparePart = new SparePart();
            sparePart.Product_Id = id;
            var list = pm.GetList(); 
            ViewBag.GetData = new SelectList(list, "Product_Id", "Product_Name");

            return View(sparePart);
        }
        [HttpPost]
        public IActionResult AddPart(SparePart p,List<Product> products)
        {
            
            sp.ProductAdd(p);
            TempData["infoaddpart"] = string.Format("{0} Part Added: {1}", p.Part_Name, DateTime.Now.ToString());
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            var list = pm.GetList();
            var spp = sp.GetById(id);
            int dd = spp.Product_Id;
            //var pmm = pm.GetById(dd);
            ViewBag.PartData = new SelectList(list, "Product_Id", "Product_Name");





            return View(spp);
        }

        [HttpPost]
        public IActionResult Update(SparePart p)
        {
            var sparePart = sp.GetById(p.Part_Id);
            sparePart.Product_Id = p.Product_Id;
            sparePart.Part_Name = p.Part_Name;
            sparePart.Part_Price = p.Part_Price;
            sp.ProductUpdate(sparePart);

            return RedirectToAction("Index");

          
        }


    }
}

OneRow/UI/Controllers/ProductController.cs
using Bll.Concrete;
using Dal.EntityFramework;
using Entity.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;

namespace UI.Controllers
{
    public class ProductController : Controller
    {
        ProductManager pm = new ProductManager(new EfProductRepository());
        SparePartManager sp = new SparePartManager(new EfSparePartRepository());
        [Authorize]
        public IActionResult Index(int page=1)
        {
           
            List<Product> products=new List<Product>();
            products = pm.GetList();
          
            return View(products.ToPagedList(page,3));
        }

        public IActionResult ProductDelete(int id)
        {
            var sparepart = sp.GetById(id);
            var product= pm.GetById(id);

            if (sparepart == null)
            {
                pm.ProductDelete(product);
                TempData["infoproductdelete"]= string.Format("{0} Product Deleted.: {1}", product.Product_Name, DateTime.Now.ToString());
            }
            else
            {
              
                TempData["infoproductdelete"] = string.Format("Not Deleted..{0} Product Has One or Many Parts: {1}", product.Product_Name, DateTime.Now.ToString());
            }
            
            return RedirectToAction("Index");

        }
        [HttpGet]
        public IActionResult AddProduct()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddProduct(Product p)
        {
          
            pm.ProductAdd(p);
            TempData["infoaddproduct"] = string.Format("{0} Product Added: {1}", p.Product_Name, DateTime.Now.ToString());
            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult GetProduct(int id)
        {
            var product = pm.GetById(id);
            Product pd = new Product();
            {
                pd.Product_Id = product.Product_Id;
                pd.Product_Name=product.Product_Name;
                pd.Sale_Price=product.Sale_Price;
            }
            return View(pd);
        }

        [HttpPost]
        public IActionResult UpdateProduct(Product p)
        {
            var up= pm.GetById(p.Product_Id);
            up.Product_Name = p.Product_Name;
            up.Sale_Price = p.Sale_Price; 
            pm.ProductUpdate(up);
            return RedirectToAction("Index");
        }


    }
}

OneRow/UI/Controllers/StartPageController.cs
using Bll.Concrete;
using Dal.EntityFramework;
using Entity.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace UI.Controllers
{
    public class StartPageController : Controller
    {
        public IActionResult Index()
        {
            ProductManager pm = new ProductManager(new EfProductRepository());
          
            int products; 
            products = pm.GetList().Count();
            ViewData["productscount"] = products;
            return View();
        
            
        }
    }
}

OneRow/UI/Views/Admin/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>Admin Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="images/icons/favicon.ico" />
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/Login_v16/vendor/bootstrap/css/bootstrap.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/Login_v16/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/Login_v16/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/Login_v16/vendor/animate/animate.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/Login_v16/vendor/css-hamburgers/hamburgers.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/Login_v16/vendor/animsition/css/animsition.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/Login_v16/vendor/select2/select2.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/Login_v16/vendor/daterangepicker/daterangepicker.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="~/Login_v16/css/util.css">
	<link rel="stylesheet" type="text/css" href="~/Login_v16/css/main.css">
	<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100" style="background-image: url('/Login_v16/images/bg-01.jpg');">
			<div class="wrap-login100 p-t-30 p-b-50">
				<span class="login100-form-title p-b-41">
					Admin Login
				</span>
				<form action="~/Admin/Index/"  method="post" class="login100-form validate-form p-b-33 p-t-5">

					<div class="wrap-input100 validate-input" data-validate = "Enter username">
						<input class="input100" type="text" name="User_Name" placeholder="User name">
						<span class="focus-input100" data-placeholder="&#xe82a;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<input class="input100" type="password" name="User_Password" placeholder="Password">
						<span class="focus-input100" data-placeholder="&#xe80f;"></span>
					</div>

					<div class="container-login100-form-btn m-t-32">
						<button class="login100-form-btn" >
							Login
						</button>
					</div>

				</form>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="~/Login_v16/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="~/Login_v16/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="~/Login_v16/vendor/bootstrap/js/popper.js"></script>
	<script src="~/Login_v16/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="~/Login_v16/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="~/Login_v16/vendor/daterangepicker/moment.min.js"></script>
	<script src="~/Login_v16/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="~/Login_v16/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="~/Login_v16//js/main.js"></script>

</body>
</html>

OneRow/UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

OneRow/UI/Views/Part/AddPart.cshtml
@using Entity.Concrete
@model SparePart

@{
    ViewData["Title"] = "AddPart";
    Layout = "~/Views/Shared/UserLayout.cshtml";
}



@if (@TempData["infoaddpart"] != null)
{
    <div class="alert alert-info">
    @TempData["infoaddpart"]
</div>
}
<h1>Add Part</h1>

@using (Html.BeginForm("AddPart","Part",FormMethod.Post))
{ 
    @Html.Label("Part Name")
    @Html.TextBoxFor(x=>x.Part_Name,new {@class= "form-control"})
    @Html.ValidationMessageFor(x=>x.Part_Name)
    <br />
    @Html.Label("Part Price")
    @Html.TextBoxFor(x=>x.Part_Price,new {@class= "form-control"})
    @Html.ValidationMessageFor(x=>x.Part_Price)
    <br />
      @Html.Label("Product Name")
              
               @Html.DropDownListFor(m => m.Product_Id, ViewBag.GetData as SelectList, new { @class = "form-control" })



    <button class="btn btn-info">Save</button>
}

OneRow/UI/Views/Part/Index.cshtml
@using Entity.DTO
@model List<SparePartDTO>
@{
    ViewData["Title"] = "Parts";
    Layout = "~/Views/Shared/UserLayout.cshtml";
}




<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />

<style>
    .addbutton{
        
            position: relative;
            right: -8px;
       
    }
</style>
@if (@TempData["infoproductdelete"] != null)
{
    <div class="alert alert-info">
    @TempData["infoproductdelete"]
</div>
}

<a  href="/Part/AddPart" class="addbutton btn btn-success">Add New Part</a>

<table class="table table-bordered">
    <tr>
        <th>
            Part Name
        </th>
        <th>
            Price
        </th>
         <th>
            Product Name
        </th>
  
         <th>
            Update
        </th>
         <th>
            Delete
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.PartName</td>
            <td>@item.Price</td>
            <td>@item.ProductName</td>
          
           <td><a href="/Part/Update/@item.PartId" class=" btn btn-warning">Update</a></td>
            <td><a href="/Part/PartDelete/@item.PartId" class=" btn btn-danger">Delete</a></td>
        </tr>
    }
</table>

OneRow/UI/Views/Part/Update.cshtml
@using Entity.Concrete
@model SparePart
@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Shared/UserLayout.cshtml";
}

<h1>Update</h1>

@using (Html.BeginForm("Update","Part",FormMethod.Post))
{   @Html.Hidden("Part_Id")
    <br />
    @Html.Label("Part Name")
    @Html.TextBoxFor(x=>x.Part_Name,new {@class= "form-control"})
    @Html.ValidationMessageFor(x=>x.Part_Name)
    <br />
    @Html.Label("Part Price")
    @Html.TextBoxFor(x=>x.Part_Price,new {@class= "form-control"})
    @Html.ValidationMessageFor(x=>x.Part_Price)
    <br />
    
       @Html.Label("Product Name")
               @Html.DropDownListFor(m => m.Product_Id, ViewBag.PartData as SelectList, new { @class = "form-control" })
    <button class="btn btn-outline-secondary">Update</button>
}

OneRow/UI/Views/Product/AddProduct.cshtml
@using Entity.Concrete
@model Product
@{
    ViewData["Title"] = "AddProduct";
    Layout = "~/Views/Shared/UserLayout.cshtml";
}
@if (@TempData["infoaddproduct"] != null)
{
    <div class="alert alert-info">
    @TempData["infoaddproduct"]
</div>
}
<h1>Add Product</h1>

@using (Html.BeginForm("AddProduct","Product",FormMethod.Post))
{
    @Html.Label("Product Name")
    @Html.TextBoxFor(x=>x.Product_Name,new {@class= "form-control"})
    @Html.ValidationMessageFor(x=>x.Product_Name)
    <br />
    @Html.Label("Product Price")
    @Html.TextBoxFor(x=>x.Sale_Price,new {@class= "form-control"})
    @Html.ValidationMessageFor(x=>x.Product_Name)
    <br />
    <button class="btn btn-info">Save</button>
}

OneRow/UI/Views/Product/GetProduct.cshtml
@using Entity.Concrete
@model Product
@{
    ViewData["Title"] = "UpdateProduct";
    Layout = "~/Views/Shared/UserLayout.cshtml";
}

<h1>Update Product</h1>

@using (Html.BeginForm("UpdateProduct","Product",FormMethod.Post))
{   @Html.Hidden("Product_Id")
    <br />
    @Html.Label("Product Name")
    @Html.TextBoxFor(x=>x.Product_Name,new {@class= "form-control"})
    @Html.ValidationMessageFor(x=>x.Product_Name)
    <br />
    @Html.Label("Product Price")
    @Html.TextBoxFor(x=>x.Sale_Price,new {@class= "form-control"})
    @Html.ValidationMessageFor(x=>x.Sale_Price)
    <br />
    <button class="btn btn-outline-secondary">Update</button>
}

OneRow/UI/Views/Product/Index.cshtml
@using Entity.Concrete
@using X.PagedList
@using X.PagedList.Mvc.Core
@model IPagedList<Product>
@{
     ViewData["Title"] = "Products";
    Layout = "~/Views/Shared/UserLayout.cshtml";
}




<style>

    .addbutton{
        
            position: relative;
            right: -8px;
       
    }
</style>
@if (@TempData["infoproductdelete"] != null)
{
    <div class="alert alert-info">
    @TempData["infoproductdelete"]
</div>
}
@if (@TempData["infoaddproduct"] != null)
{
    <div class="alert alert-info">
    @TempData["infoaddproduct"]
</div>
}


<a  href="/Product/AddProduct" class="addbutton btn btn-success">Add New Product</a>
<table class="table table-bordered">
    <tr>
       
        <th>
            Product Name
        </th>
        <th>
            Price
        </th>
         <th>
            Add
        </th>
         <th>
            Update
        </th>
         <th>
            Delete
        </th>
       
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            

            <td>@item.Product_Name</td>
            <td>@item.Sale_Price</td>
            <td><a href="/Part/AddPart/@item.Product_Id" class=" btn btn-success">Add New Part</a></td>
            <td><a href="/Product/GetProduct/@item.Product_Id" class=" btn btn-warning">Update</a></td>
            <td><a href="/Product/ProductDelete/@item.Product_Id" class=" btn btn-danger">Delete</a></td>
            
        </tr>
        
    }
       <tr>
            <td  align="center">
                <pager list="@Model" asp-controller="Product" asp-action="Index"/>
            </td>
        </tr>
</table>
<div class="center">
@Html.PagedListPager((IPagedList)Model,page=>Url.Action("Index",new {page}))
</div>


<style>
    .center {
        margin-left: auto;
  margin-right: auto;
  
  width: 3%;

 display: block;
  
}
</style>

OneRow/UI/Views/Shared/UserLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title> </title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="Free Website Template" name="keywords">
        <meta content="Free Website Template" name="description">

        <!-- Favicon -->
        <link href="img/favicon.ico" rel="icon">

        <!-- Google Font -->
        <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@400;500;600;700;800;900&display=swap" rel="stylesheet"> 
        
        <!-- CSS Libraries -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="~/Template/lib/flaticon/font/flaticon.css" rel="stylesheet">
        <link href="~/Template/lib/animate/animate.min.css" rel="stylesheet">
        <link href="~/Template/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">
		<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UI.styles.css" asp-append-version="true" />
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <!-- Template Stylesheet -->
        <link href="~/Template/css/style.css" rel="stylesheet">
    </head>

    <body>
        <!-- Top Bar Start -->
        <div class="top-bar">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-4 col-md-12">
                        <div class="logo">
                            <a href="#">
                                <h1>One<span>Row</span></h1>
                                <!-- <img src="img/logo.jpg" alt="Logo"> -->
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-8 col-md-7 d-none d-lg-block">
                        <div class="row">
                            <div class="col-4">
                                <div class="top-bar-item">
                                    <div class="top-bar-icon">
                                        <i class="far fa-clock"></i>
                                    </div>
                                    <div class="top-bar-text">
                                        <h3>Opening Hour</h3>
                                        <p>Mon - Fri, 8:00 - 9:00</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="top-bar-item">
                                    <div class="top-bar-icon">
                                        <i class="fa fa-phone-alt"></i>
                                    </div>
                                    <div class="top-bar-text">
                                        <h3>Call Us</h3>
                                        <p>+012 345 6789</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="top-bar-item">
                                    <div class="top-bar-icon">
                                        <i class="far fa-envelope"></i>
                                    </div>
                                    <div class="top-bar-text">
                                        <h3>Email Us</h3>
                                        <p>info@example.com</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Top Bar End -->

        <!-- Nav Bar Start -->
        <div class="nav-bar">
            <div class="container">
                <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
                    <a href="#" class="navbar-brand">MENU</a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav mr-auto">
                           
                            <a href="/product/Index" class="nav-item nav-link">Products</a>
                            <a href="/part/Index" class="nav-item nav-link">Parts</a>
                           
                           
                           
                        </div>
                        <div class="ml-auto">
                            <a class="btn btn-custom" href="/Admin/Index">Admin</a>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
        <!-- Nav Bar End -->



        @RenderBody()
        
       

        <!-- Footer Start -->
        <div class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-contact">
                            <h2>Get In Touch</h2>
                            <p><i class="fa fa-map-marker-alt"></i>123 Street, New York, USA</p>
                            <p><i class="fa fa-phone-alt"></i>+012 345 67890</p>
                            <p><i class="fa fa-envelope"></i>info@example.com</p>
                            <div class="footer-social">
                                <a class="btn" href=""><i class="fab fa-twitter"></i></a>
                                <a class="btn" href=""><i class="fab fa-facebook-f"></i></a>
                                <a class="btn" href=""><i class="fab fa-youtube"></i></a>
                                <a class="btn" href=""><i class="fab fa-instagram"></i></a>
                                <a class="btn" href=""><i class="fab fa-linkedin-in"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-link">
                            <h2>Popular Links</h2>
                            <a href="">About Us</a>
                            <a href="">Contact Us</a>
                            <a href="">Our Service</a>
                            <a href="">Service Points</a>
                            <a href="">Pricing Plan</a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-link">
                            <h2>Useful Links</h2>
                            <a href="">Terms of use</a>
                            <a href="">Privacy policy</a>
                            <a href="">Cookies</a>
                            <a href="">Help</a>
                            <a href="">FQAs</a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-newsletter">
                            <h2>Newsletter</h2>
                            <form>
                                <input class="form-control" placeholder="Full Name">
                                <input class="form-control" placeholder="Email">
                                <button class="btn btn-custom">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container copyright">
                <p>&copy; <a href="#">Your Site Name</a>, All Right Reserved. Designed By </p>
            </div>
        </div>
        <!-- Footer End -->
        
        <!-- Back to top button -->
        <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
        
        <!-- Pre Loader -->
        <div id="loader" class="show">
            <div class="loader"></div>
        </div>

        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src="~/Template/lib/easing/easing.min.js"></script>
        <script src="~/Template/lib/owlcarousel/owl.carousel.min.js"></script>
        <script src="~/Template/lib/waypoints/waypoints.min.js"></script>
        <script src="~/Template/lib/counterup/counterup.min.js"></script>
                  
        <!-- Contact ~/Javascript File -->
        <script src="~/Template/mail/jqBootstrapValidation.min.js"></script>
       
        <script src="~/Template/mail/contact.js"></script>
         <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

      
    <!-- Template Javascript -->
        <script src="~/Template/js/main.js"></script>
    </body>
</html>

OneRow/UI/Views/StartPage/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/UserLayout.cshtml";
   
}
<div class="facts" data-parallax="scroll" data-image-src="img/facts.jpg">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="facts-item">
                            <i class="fas fa-car"></i>
                            <div class="facts-text">
                                <h3 data-toggle="counter-up">@ViewData["productscount"]</h3>
                                <p>Products</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="facts-item">
                            <i class="fa fa-user"></i>
                            <div class="facts-text">
                                <h3 data-toggle="counter-up">350</h3>
                                <p>Engineers &amp; Workers</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="facts-item">
                            <i class="fa fa-users"></i>
                            <div class="facts-text">
                                <h3 data-toggle="counter-up">1500</h3>
                                <p>Happy Clients</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="facts-item">
                            <i class="fa fa-check"></i>
                            <div class="facts-text">
                                <h3 data-toggle="counter-up">5000</h3>
                                <p>Projects Completed</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

                     